Not just a CMS
==============
meh. <meh.ffff@gmail.com>

_miniLOL_ is a highly modular CMS written in Javascript, but it's more than that, it's a development platform.

_miniLOL_ comes with some useful libraries and extensions for module developers, and the event driven nature
of _miniLOL_ makes it easy to develop modules that interact with the content.

Why Javascript?
---------------

Well, at first _miniLOL_ was written to be used by me on a slow server, so having less work load on the server
was a good idea, because it would be faster.

I'm deliberately going against the web trend of cloud computing because I don't see it as a good thing.

Why having 100 people downloading content that's been generated by a server would be better than having those 100 people
generate the content from some XML files?

I think it's a pretty neat idea having everything on the client side.

How can it be a CMS if everything happens in the browser?
---------------------------------------------------------

The core is Javascript only, modules are written in JS and can have the backend in whatever language you want.

This means that on a server that has CGI with C you can write your own backend and everything will work as expected.

In this way you can put _miniLOL_ on embedded hardware as long as there's a web server that can serve static files.

The _Blog_ module for example can be used without the PHP backend, you just have to edit the XML file and upload it
to the server, and the blog will be updated.

But Javascript can't be indexed by search engines
-------------------------------------------------

Well, I *DO NOT WANT* to be indexed, but I know most do, so there's a _Static_ module which is a PHP implementation of _miniLOL_.

It's modular as well, so you can get module adapters that make real modules work in the _Static_ version and there are
even _Static_ modules, like _URL Rewrite_ that enables Apache URL rewriting.

It's obviously less powerfull than the real one, but you should use it just to give content to search engines or text browsers,
so deal with it.
